[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip

board = jc4827w543c
framework = arduino
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -I src

upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101

board_build.flash_size = 4MB
;board_build.partitions = default.csv
board_build.partitions = min_spiffs.csv
board_build.arduino.memory_type = qio_opi

;upload_flags =
;    --before=default_reset
;    --after=hard_reset
;    --chip=esp32s3

lib_deps =
    moononournation/GFX Library for Arduino @ ^1.4.9
    lvgl/lvgl @ ^8.4.0