// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: intercooler

#ifndef _UI_COMP_TOPPANEL1_H
#define _UI_COMP_TOPPANEL1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT topPanel1
#define UI_COMP_TOPPANEL1_TOPPANEL1 0
#define UI_COMP_TOPPANEL1_BUTTON1 1
#define UI_COMP_TOPPANEL1_BUTTON2 2
#define _UI_COMP_TOPPANEL1_NUM 3
lv_obj_t *ui_topPanel1_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
