// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: intercooler

#ifndef UI_INTERCOLLER_H
#define UI_INTERCOLLER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_intercoller
extern void ui_intercoller_screen_init(void);
extern void ui_intercoller_screen_destroy(void);
extern lv_obj_t *ui_intercoller;
extern lv_obj_t *ui_topPanel1;
extern void ui_event_btnScreen1( lv_event_t * e);
extern lv_obj_t *ui_btnScreen1;
extern lv_obj_t *ui_Label5;
extern void ui_event_btnScreen3( lv_event_t * e);
extern lv_obj_t *ui_btnScreen3;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_lblCoolantIn;
extern lv_obj_t *ui_brCoolantIn;
extern lv_obj_t *ui_lblCoolantOut;
extern lv_obj_t *ui_brCoolantOut;
extern lv_obj_t *ui_brAirIn;
extern lv_obj_t *ui_lblAirIn;
extern lv_obj_t *ui_brAirOut;
extern lv_obj_t *ui_lblAirOut;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

