// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: intercooler

#ifndef UI_LIGHT_H
#define UI_LIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_light
extern void ui_light_screen_init(void);
extern void ui_light_screen_destroy(void);
extern lv_obj_t *ui_light;
extern lv_obj_t *ui_topPanel2;
extern void ui_event_btnScreen2( lv_event_t * e);
extern lv_obj_t *ui_btnScreen2;
extern lv_obj_t *ui_Label1;
extern void ui_event_btnScreen4( lv_event_t * e);
extern lv_obj_t *ui_btnScreen4;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_swFrontLeft;
extern lv_obj_t *ui_swFrontRight;
extern lv_obj_t *ui_swHeadLeft;
extern lv_obj_t *ui_swHeadRight;
extern lv_obj_t *ui_swSyncOn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

