// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Intercooler

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_topPanel1 = NULL;lv_obj_t *ui_btnScreen1 = NULL;lv_obj_t *ui_Arc3 = NULL;lv_obj_t *ui_Arc4 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Bar1 = NULL;lv_obj_t *ui_Bar2 = NULL;lv_obj_t *ui_Slider1 = NULL;
// event funtions
void ui_event_btnScreen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen1_screen_init);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_topPanel1 = lv_obj_create(ui_Screen1);
lv_obj_set_height( ui_topPanel1, 25);
lv_obj_set_width( ui_topPanel1, lv_pct(100));
lv_obj_set_align( ui_topPanel1, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_topPanel1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_topPanel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_topPanel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnScreen1 = lv_btn_create(ui_topPanel1);
lv_obj_set_width( ui_btnScreen1, 100);
lv_obj_set_height( ui_btnScreen1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_btnScreen1, -142 );
lv_obj_set_y( ui_btnScreen1, 0 );
lv_obj_set_align( ui_btnScreen1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnScreen1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnScreen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc3 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc3, 128);
lv_obj_set_height( ui_Arc3, 128);
lv_obj_set_x( ui_Arc3, -150 );
lv_obj_set_y( ui_Arc3, 0 );
lv_obj_set_align( ui_Arc3, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc3, -50,150);
lv_arc_set_value(ui_Arc3, 0);
lv_arc_set_bg_angles(ui_Arc3,100,260);

ui_Arc4 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc4, 128);
lv_obj_set_height( ui_Arc4, 128);
lv_obj_set_x( ui_Arc4, -102 );
lv_obj_set_y( ui_Arc4, 0 );
lv_obj_set_align( ui_Arc4, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc4, -50,150);
lv_arc_set_value(ui_Arc4, 0);
lv_arc_set_bg_angles(ui_Arc4,280,80);
lv_arc_set_mode(ui_Arc4, LV_ARC_MODE_REVERSE);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_1701475388);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 50 );
lv_obj_set_y( ui_Image1, 0 );
lv_obj_set_align( ui_Image1, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image2, &ui_img_2140865956);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, -50 );
lv_obj_set_y( ui_Image2, 0 );
lv_obj_set_align( ui_Image2, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Bar1 = lv_bar_create(ui_Screen1);
lv_bar_set_range(ui_Bar1, -50,150);
lv_obj_set_width( ui_Bar1, 10);
lv_obj_set_height( ui_Bar1, 128);
lv_obj_set_x( ui_Bar1, 50 );
lv_obj_set_y( ui_Bar1, 0 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );

ui_Bar2 = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_Bar2,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar2, 10);
lv_obj_set_height( ui_Bar2, 128);
lv_obj_set_x( ui_Bar2, 210 );
lv_obj_set_y( ui_Bar2, -1 );
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );

ui_Slider1 = lv_slider_create(ui_Screen1);
lv_slider_set_range(ui_Slider1, -50,150);
lv_slider_set_value( ui_Slider1, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_height( ui_Slider1, 10);
lv_obj_set_width( ui_Slider1, lv_pct(90));
lv_obj_set_x( ui_Slider1, 0 );
lv_obj_set_y( ui_Slider1, -20 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_BOTTOM_MID );

lv_obj_add_event_cb(ui_btnScreen1, ui_event_btnScreen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_topPanel1= NULL;
ui_btnScreen1= NULL;
ui_Arc3= NULL;
ui_Arc4= NULL;
ui_Image1= NULL;
ui_Image2= NULL;
ui_Bar1= NULL;
ui_Bar2= NULL;
ui_Slider1= NULL;

}
