// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: intercooler

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_topPanel1;
extern void ui_event_btnScreen1( lv_event_t * e);
extern lv_obj_t *ui_btnScreen1;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_lblCoolantIn;
extern lv_obj_t *ui_brCoolantIn;
extern lv_obj_t *ui_lblCoolantOut;
extern lv_obj_t *ui_brCoolantOut;
extern lv_obj_t *ui_brAirIn;
extern lv_obj_t *ui_lblAirIn;
extern lv_obj_t *ui_brAirOut;
extern lv_obj_t *ui_lblAirOut;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

